apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: imagebuilder-daemonset
spec:
  selector:
    matchLabels:
      app: imagebuilder
  template:
    metadata:
      labels:
        app: imagebuilder
    spec:
      serviceAccountName: imagebuilder-service-account
      containers:
        - name: imagebuilder-container
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: zichenkkkk/imagebuilder:1.9.3
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: containerd-socket
              mountPath: /run/containerd/containerd.sock
          securityContext:
            privileged: true
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagebuilder-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-and-node-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "imagebuilder.ai.qingcloud.com" ]
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagebuilder-pod-and-node-reader
subjects:
  - kind: ServiceAccount
    name: imagebuilder-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-and-node-reader
  apiGroup: rbac.authorization.k8s.io